---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: silver-ublue
description: A custom image of an already amazing immutable linux distro 

# Builds the image on top of silverblue-main's latest version
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest

modules:
  # Updates the os-release file (The manifest that defines what version the OS is)
  - type: script
    scripts:
      - UpdateOSRelease.sh
  # Enables UUPD (Universal Update)
  # Normally this is supposed to be provided by bling (https://blue-build.org/reference/modules/bling/)
  # but it isn't (for now). So we install it through recipe.yml, then configure it here.
  - type: dnf
    repos:
      copr:
        - ublue-os/packages
    install:
      packages:
        - uupd
    remove:
      packages:
        - ublue-os-update-services
  - type: script
    scripts:
      - EnableUUPD.sh
  # Integrates NVIDIA-OPEN Drivers
  - type: akmods
    base: main
    install: [] # This is required but we don't want anything other than NVIDIA but that uses nvidia-driver
    nvidia-driver: nvidia-open
  - type: dnf
    install:
      packages:
        - libva-nvidia-driver # Video Decoding Implementation for NVIDIA GPUs (Firefox)
    remove:
      packages:
        - nvidia-settings # NVIDIA X Server Settings (X11 is not available in GNOME)
        - nvidia-libXNVCtrl # NVIDIA X Server Settings dependency.
  - type: script
    scripts:
      - ConfigureVAAPI.sh # Configure Video Decoding for NVIDIA GPUs
  # Configures DNS-over-TLS for secure connections
  - type: files
    files:
      - source: resolved.conf.d
        destination: /etc/systemd/resolved.conf.d
  # Installs zapret, a DPI bypass tool.
  # more info @ https://github.com/bol-van/zapret/blob/master/docs/readme.en.md
  - type: dnf
    repos:
      files:
        - https://github.com/terrapkg/subatomic-repos/raw/main/terra.repo
    install:
      packages:
        - zapret
  - type: files
    files:
      - source: zapret
        destination: /etc/zapret
  - type: script
    scripts:
      - EnableZapret.sh
  # Configures GNOME with gschema overrides @ files/gschema-overrides/*
  - type: gschema-overrides
  # Configures Inbox apps that are shipped with the image
  - type: dnf
    install:
      packages:
        - fastfetch
    remove:
      packages:
        # removes firefox (in favor of the flatpak)
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
        - toolbox
        - gnome-classic-session
        - gnome-tour
        - yelp
        - gnome-software # Replaces GNOME Software in favor of Bazaar
        # These get installed by the previous modules but aren't needed to keep the image as simple as possible
        - htop # (NVIDIA)
        - nvtop # (NVIDIA)
        - dconf-editor # (GSchema Overrides)
  - type: default-flatpaks
    configurations:
      # Disables Fedora Flatpak and uses Flathub exclusively. Users decide what apps they want.
      - scope: user
        repo:
          title: Flathub
      - scope: system
        repo:
          title: Flathub (System)
        install: # system flatpaks we want all users to have and not remove
          - io.github.kolunmi.Bazaar # Bazaar App Store (in favor of gnome-software)
          - com.github.tchx84.Flatseal
          - org.gnome.Calculator
          - org.gnome.Calendar
          #- org.gnome.Characters
          - org.gnome.Logs # GNOME Logs
          - org.gnome.Loupe # Image Viewer
          - org.gnome.NautilusPreviewer # GNOME Sushi
          - org.gnome.Papers # Document Viewer
          #- org.gnome.Snapshot # Camera
          - org.gnome.TextEditor
          - org.gnome.Weather
          - org.gnome.baobab # Disk Usage Analyzer
          - org.gnome.clocks
          #- org.gnome.font-viewer
  # Runs a "Prepare for First Use" script before the image is packaged and signed.
  - type: script
    scripts:
      - PrepareForFirstUse.sh
  # Enables Numpad on boot during disk encryption process (Plymouth)
  # MAKE SURE THIS IS LAST BEFORE SIGNING because it's recommended to put the initramfs module that way.
  - type: files
    files:
      - source: dracut-numlock
        destination: /usr/lib/dracut/modules.d/50numlock
  - type: initramfs
  # Configure image signing and security policy - REQUIRED
  - type: signing
