---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: silver-ublue
# description will be included in the image's metadata
description: A custom image of an already amazing immutable linux distro 

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest # latest is also supported if you want new updates ASAP

modules:
  # Copies files to the container image
  #- type: files
  #  files:
  #    - source: system
  #      destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
  # Configures Default Packages from DNF
  - type: dnf
    install:
      packages:
        - fastfetch
    remove:
      packages:
        # removes firefox (in favor of the flatpak)
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
        - toolbox
        - gnome-classic-session
        - gnome-tour
  # Integrates NVIDIA-OPEN Drivers
  - type: akmods
    base: main
    install: # This is required but we don't want anything other than NVIDIA but that uses nvidia-driver
    nvidia-driver: nvidia-open
  # Configures default flatpaks
  - type: default-flatpaks
    configurations:
      # Disables Fedora Flatpak and uses Flathub (User) exclusively. Users decide what apps they want.
      - scope: user
  # Configures GNOME
  - type: gschema-overrides
    include:
      - org.gnome.mutter.gschema.override 
      - org.gnome.desktop.gschema.override
  # Runs a "Prepare for First Use" script before the image is packaged and signed.
  - type: script
    scripts:
      - PrepareForFirstUse.sh
  # Configure image signing and security policy - REQIRED
  - type: signing
