---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: silver-ublue
description: A custom image of an already amazing immutable linux distro 

# Builds the image on top of silverblue-main's latest version
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest

modules:
  # Copies files to the container image
  #- type: files
  #  files:
  #    - source: system
  #      destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
  # Configures Default Packages from DNF
  - type: dnf
    repos:
      copr:
        - ublue-os/packages
    install:
      packages:
        - fastfetch
        - uupd
    remove:
      packages:
        # removes firefox (in favor of the flatpak)
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
        - toolbox
        - gnome-classic-session
        - gnome-tour
        - yelp
        - ublue-os-update-services
  # Enables UUPD (Universal Update)
  # Normally this is supposed to be provided by bling (https://blue-build.org/reference/modules/bling/)
  # but it isn't (for now). So we install it through recipe.yml, then configure it here.
  - type: script
    scripts:
      - EnableUUPD.sh
  # Integrates NVIDIA-OPEN Drivers
  - type: akmods
    base: main
    install: [] # This is required but we don't want anything other than NVIDIA but that uses nvidia-driver
    nvidia-driver: nvidia-open
  # Configures default flatpaks
  - type: default-flatpaks
    configurations:
      # Disables Fedora Flatpak and uses Flathub exclusively. Users decide what apps they want.
      - scope: user
        repo:
          title: Flathub
      - scope: system
        repo:
          title: Flathub (System)
        install: # system flatpaks we want all users to have and not remove
          - com.github.tchx84.Flatseal
          - org.gnome.Calculator
          - org.gnome.Calendar
          - org.gnome.Characters
          - org.gnome.Logs # GNOME Logs
          - org.gnome.Loupe # Image Viewer
          - org.gnome.NautilusPreviewer # GNOME Sushi
          - org.gnome.Papers # Document Viewer
          - org.gnome.Snapshot # Camera
          - org.gnome.TextEditor
          - org.gnome.Weather
          - org.gnome.baobab # Disk Usage Analyzer
          - org.gnome.clocks
          - org.gnome.font-viewer
  # Configures GNOME
  - type: gschema-overrides
  # Runs a "Prepare for First Use" script before the image is packaged and signed.
  - type: script
    scripts:
      - PrepareForFirstUse.sh
  # Configure image signing and security policy - REQIRED
  - type: signing
