---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: silverblue
description: A rock solid immutable linux image based on Universal Blue

# Builds the image on top of silverblue-main's latest version
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest

modules:
  # Updates the os-release file (The manifest that defines what version the OS is)
  - type: script
    scripts:
      - UpdateOSRelease.sh
  # Enables UUPD (Universal Update)
  # Normally this is supposed to be provided by bling (https://blue-build.org/reference/modules/bling/)
  # but it isn't (for now). So we install it through recipe.yml, then configure it here.
  - type: dnf
    repos:
      copr:
        - ublue-os/packages
    install:
      packages:
        - uupd
    remove:
      packages:
        - ublue-os-update-services
  - type: script
    scripts:
      - EnableUUPD.sh
  # Integrates NVIDIA Drivers
  - type: akmods
    base: main
    install: [] # This is required but we don't want anything other than NVIDIA but that uses nvidia-driver
    nvidia-driver: nvidia-open
  - type: dnf
    install:
      packages:
        - libva-nvidia-driver
    remove:
      packages:
        - nvidia-settings # NVIDIA X Server Settings (X11 is not available in GNOME so we don't need it)
        - nvidia-libXNVCtrl # NVIDIA X Server Settings dependency.
        - htop
        - nvtop
  - type: script
    scripts:
      - ConfigureNVIDIA.sh
  # Lets go with the defaults!
  #- type: kargs
  #  kargs:
  #    #- nvidia-drm.modeset=1 # Fedora enables it anyway, and enabling it from here may actually mess with fedora (check https://rpmfusion.org/Howto/NVIDIA#KMS to see why its disabled)
  #    - nvidia-drm.fbdev=1 # Lets the terminal use the display resolution, might be required for wayland (https://wiki.archlinux.org/title/NVIDIA#fbdev)
  #    - nvidia.NVreg_UsePageAttributeTable=1 # PAT can increase performance (https://wiki.archlinux.org/title/NVIDIA/Tips_and_tricks#Kernel_module_parameters)
  #    - nvidia.NVreg_PreserveVideoMemoryAllocations=1 # Screen corruption after resuming from suspend (https://wiki.archlinux.org/title/NVIDIA/Tips_and_tricks#Preserve_video_memory_after_suspend)
  #    - nvidia.NVreg_TemporaryFilePath=/var/tmp # Screen corruption after resuming from suspend (https://wiki.archlinux.org/title/NVIDIA/Tips_and_tricks#Preserve_video_memory_after_suspend)
  #    - nvidia.NVreg_DynamicPowerManagement=0x02 # Display corruption after reboot on GNOME (https://wiki.archlinux.org/title/NVIDIA/Troubleshooting#Fix_graphical_corruption_in_GNOME_Shell_when_resuming_from_sleep)
  # Configures DNS-over-TLS for secure connections
  - type: files
    files:
      - source: resolved.conf.d
        destination: /etc/systemd/resolved.conf.d
  # Installs zapret, a DPI bypass tool.
  # more info @ https://github.com/bol-van/zapret/blob/master/docs/readme.en.md
  - type: dnf
    repos:
      files:
        - https://github.com/terrapkg/subatomic-repos/raw/main/terra.repo
    install:
      packages:
        - zapret
  - type: files
    files:
      - source: zapret
        destination: /etc/zapret
  # Configures GNOME with gschema overrides @ files/gschema-overrides/*
  # and extensions
  - type: gnome-extensions
    install:
      - 2236 # Night Theme Switcher
      - 615 # AppIndicator and KStatusNotifierItem Support (System Tray)
      - 7048 # Rounded Window Corners Reborn
      - 8692 # "In Picture" - Fixes PiP in Wayland until native support arrives
  - type: gschema-overrides
  # Configures Inbox apps that are shipped with the image
  - type: dnf
    install:
      packages:
        - fastfetch
        - adw-gtk3-theme # Libadwaita theme for gtk3 apps
    remove:
      packages:
        # removes firefox (in favor of the flatpak)
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
        - toolbox
        - gnome-classic-session
        - gnome-tour
        - yelp
        - gnome-software # Replaces GNOME Software in favor of Bazaar
        - gnome-software-rpm-ostree
        - gnome-firmware
        - dconf-editor # (GSchema Overrides)
  - type: default-flatpaks
    configurations:
      # Disables Fedora Flatpak and uses Flathub exclusively.
      # These are system flatpaks we want all users to have and not remove
      - notify: false
        scope: user
        repo:
          title: Flathub
      - notify: false
        scope: system
        repo:
          title: Flathub (System)
        install: 
          - io.github.kolunmi.Bazaar # Bazaar App Store (in favor of gnome-software)
          - com.github.tchx84.Flatseal
          - org.gnome.Calculator
          - org.gnome.Calendar
          - org.gnome.Logs # GNOME Logs
          - org.gnome.Loupe # Image Viewer
          - org.gnome.NautilusPreviewer # GNOME Sushi
          - org.gnome.Papers # Document Viewer
          - org.gnome.TextEditor
          - org.gnome.Weather
          - org.gnome.baobab # Disk Usage Analyzer
          - org.gnome.clocks
          - org.gnome.Firmware
          - org.gtk.Gtk3theme.adw-gtk3 # Libadwaita theme for gtk3 apps
          - org.gtk.Gtk3theme.adw-gtk3-dark # Libadwaita theme for gtk3 apps

          # These arent installed by default and its optional
          #- org.gnome.Characters
          #- org.gnome.font-viewer
          #- org.gnome.Snapshot # Camera
  # Runs a "Prepare for First Use" script before the image is packaged and signed.
  - type: script
    scripts:
      - PrepareForFirstUse.sh
  # Enables Numpad on boot during disk encryption process (Plymouth)
  # MAKE SURE THIS IS LAST BEFORE SIGNING because it's recommended to put the initramfs module that way.
  - type: files
    files:
      - source: dracut-numlock
        destination: /usr/lib/dracut/modules.d/50numlock
  - type: initramfs
  # Configure image signing and security policy - REQUIRED
  - type: signing
